"""add_session_audio_files

Revision ID: 02af88d664fa
Revises: e3456a75212d
Create Date: 2026-04-25 11:19:21.709696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02af88d664fa'
down_revision: Union[str, Sequence[str], None] = 'e3456a75212d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('s3_raw_key', sa.String(length=1000), nullable=True),
    sa.Column('s3_prefix', sa.String(length=1000), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_order', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='audiofileprocessingstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_audio_files_created_by_user_id'), 'session_audio_files', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_session_audio_files_file_order'), 'session_audio_files', ['file_order'], unique=False)
    op.create_index(op.f('ix_session_audio_files_id'), 'session_audio_files', ['id'], unique=False)
    op.create_index(op.f('ix_session_audio_files_processing_status'), 'session_audio_files', ['processing_status'], unique=False)
    op.create_index(op.f('ix_session_audio_files_session_id'), 'session_audio_files', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_audio_files_session_id'), table_name='session_audio_files')
    op.drop_index(op.f('ix_session_audio_files_processing_status'), table_name='session_audio_files')
    op.drop_index(op.f('ix_session_audio_files_id'), table_name='session_audio_files')
    op.drop_index(op.f('ix_session_audio_files_file_order'), table_name='session_audio_files')
    op.drop_index(op.f('ix_session_audio_files_created_by_user_id'), table_name='session_audio_files')
    op.drop_table('session_audio_files')
    # ### end Alembic commands ###
