"""add editorial review flags for generated content

Revision ID: 7d21f6b31f77
Revises: b20a3e019d21
Create Date: 2026-05-25 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7d21f6b31f77"
down_revision: Union[str, Sequence[str], None] = "b20a3e019d21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "generated_content",
        sa.Column(
            "ai_generated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="True when content was generated by AI workflow",
        ),
    )
    op.add_column(
        "generated_content",
        sa.Column(
            "editorially_reviewed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="True when editorially reviewed and approved",
        ),
    )

    op.create_index(
        op.f("ix_generated_content_ai_generated"),
        "generated_content",
        ["ai_generated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_content_editorially_reviewed"),
        "generated_content",
        ["editorially_reviewed"],
        unique=False,
    )

    # Backfill: content generated through workflow execution is AI-generated.
    op.execute("""
        UPDATE generated_content
        SET ai_generated = TRUE
        WHERE workflow_execution_id IS NOT NULL
        """)

    op.alter_column("generated_content", "ai_generated", server_default=None)
    op.alter_column("generated_content", "editorially_reviewed", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_generated_content_editorially_reviewed"), table_name="generated_content")
    op.drop_index(op.f("ix_generated_content_ai_generated"), table_name="generated_content")

    op.drop_column("generated_content", "editorially_reviewed")
    op.drop_column("generated_content", "ai_generated")
