"""Add session_popularity table

Revision ID: 85aaad85971b
Revises: 394aa465482b
Create Date: 2026-04-29 23:12:45.000521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85aaad85971b'
down_revision: Union[str, Sequence[str], None] = '394aa465482b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_popularity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('acceptance_count', sa.Integer(), nullable=False),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'event_id', name='uq_session_popularity_per_event')
    )
    op.create_index(op.f('ix_session_popularity_event_id'), 'session_popularity', ['event_id'], unique=False)
    op.create_index(op.f('ix_session_popularity_id'), 'session_popularity', ['id'], unique=False)
    op.create_index(op.f('ix_session_popularity_session_id'), 'session_popularity', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_popularity_session_id'), table_name='session_popularity')
    op.drop_index(op.f('ix_session_popularity_id'), table_name='session_popularity')
    op.drop_index(op.f('ix_session_popularity_event_id'), table_name='session_popularity')
    op.drop_table('session_popularity')
    # ### end Alembic commands ###
