"""Add published_documentation_artifact column to sessions

Revision ID: 89c13d4cc639
Revises: 85aaad85971b
Create Date: 2026-05-11 18:25:27.451575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c13d4cc639'
down_revision: Union[str, Sequence[str], None] = '85aaad85971b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('published_documentation_artifact', sa.JSON(), nullable=True, comment='Versioned published session documentation artifact (JSON)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'published_documentation_artifact')
    # ### end Alembic commands ###
